title:             Jim van der Heijden
email:             230160@buas.nl
description:       Graphics programmer
author:            Jim
#url:               "localhost:4000"
url:               "https://j111m.github.io/"
baseurl:

# Social Profiles
#twitter_username:  Jim
github_username:   J111M
#facebook_username: Jim

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
